{% set version="2.0.1" %}
{% set minor_version=".".join(version.split(".")[:2]) %}

package:
  name: openmpi
  version: {{ version }}

source:
  fn: openmpi-{{ version }}.tar.bz2
  url: http://www.open-mpi.org/software/ompi/v{{ minor_version }}/downloads/openmpi-{{ version }}.tar.bz2
  sha1: cd1f825f2b94a97e78e4ae580544e9e3c56809f9

build:
  number: 0
  skip: True   # [win]
  binary_relocation: true
  detect_binary_files_with_prefix: true

test:
  commands:
    - mpicc --help
    - mpif90 --help  # [linux]

about:
  home: http://www.open-mpi.org/
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source Message Passing Interface implementation
  description: |
    The Open MPI Project is an open source Message Passing Interface
    implementation that is developed and maintained by a consortium of academic,
    research, and industry partners.
  doc_url: https://www.open-mpi.org/doc/
  dev_url: https://github.com/open-mpi/ompi

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - minrk
